import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import Header from './Header';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';

type Params = {
  courseName?: string;
  programName?: string;
};

const inferLanguage = (course: string, fileName: string): string => {
  const lowerCourse = course.toLowerCase();
  const lowerFile = fileName.toLowerCase();

  if (lowerCourse === 'dbms' || lowerFile.endsWith('.sql')) return 'sql';
  if (lowerCourse === 'mp' || lowerFile.endsWith('.asm')) return 'nasm';
  if (lowerFile.endsWith('.pl')) return 'perl';
  if (lowerFile.endsWith('.sh')) return 'bash';
  if (lowerFile.endsWith('.awk')) return 'awk';

  // DAA files are text files that contain algorithm programs.
  if (lowerCourse === 'daa') return 'cpp';

  return 'text';
};

const SAMPLE_OUTPUTS: Record<string, Record<string, string>> = {
  daa: {
    bubbleSort: `Enter the size of array:
5
Enter the elements:
64 34 25 12 22
Array is :
64 34 25 12 22
Sorted Array :
12 22 25 34 64`,
    mergeSort: `Enter array size:
6
Enter array:
38 27 43 3 9 82
Sorted array:
3 9 27 38 43 82`,
    selectionSort: `Enter the size of array:
5
Enter the elements:
29 10 14 37 13
Array is :
29 10 14 37 13
Sorted Array :
10 13 14 29 37`,
    stringMatch: `Enter Text:
ABAAABCD
Enter Pattern:
ABC
Length of text: 8
Length of pattern: 3
Pattern found at 5`,
    bfs: `Enter the number of nodes:4
Enter the number of edges:4
Enter Source:0 Enter Destination:1
Enter Source:0 Enter Destination:2
Enter Source:1 Enter Destination:2
Enter Source:2 Enter Destination:3
Adjacency Matrix:
0 1 1 0
1 0 1 0
1 1 0 1
0 0 1 0
Visiting Order:
Vertex 0 is visited 1
Vertex 1 is visited 2
Vertex 2 is visited 3
Vertex 3 is visited 4`,
    dfs: `Enter the number of nodes:4
Enter the number of edges:3
Enter Source:0 Enter Destination:1
Enter Source:1 Enter Destination:2
Enter Source:2 Enter Destination:3
Adjacency Matrix:
0 1 0 0
1 0 1 0
0 1 0 1
0 0 1 0
Visiting Order:
Vertex 0 is visited 1
Vertex 1 is visited 2
Vertex 2 is visited 3
Vertex 3 is visited 4`,
    insertionSort: `Enter size of array:5
Enter Array:
9 5 1 4 3
Sorted Array:
1 3 4 5 9`,
    quicksort: `Enter the size of array: 6
Enter the array elements:
10 7 8 9 1 5
Sorted Array:
1 5 7 8 9 10`,
    topo: `Enter the number of nodes:6
Enter the number of edges:6
Edges: (5,2) (5,0) (4,0) (4,1) (2,3) (3,1)
Topological Order:
4 5 2 0 3 1`,
    floyd: `Enter the number of vertices:4
Enter the initial matrix:
0 5 10000 10
10000 0 3 10000
10000 10000 0 1
10000 10000 10000 0
All pair shortest path matrix:
0 5 8 9
10000 0 3 4
10000 10000 0 1
10000 10000 10000 0`,
    heapSort: `Enter the number of elements:6
Enter the elements:12 11 13 5 6 7
sorted array is:
5 6 7 11 12 13`,
    horsepool: `Enter text: HEREISASIMPLEEXAMPLE
Enter pattern: EXAMPLE
Pattern found at position 13`,
    knapsack: `Enter the number of items:4
Enter the weights of items:1 3 4 5
Enter the values of items:1 4 5 7
Enter the max capacity of knapsack:7
Optimal solution is: 9`,
    warshall: `Enter the number of vertices:4
Enter the adjacency matrix:
0 1 0 0
0 0 1 0
0 0 0 1
0 0 0 0
Transitive Closure:
0 1 1 1
0 0 1 1
0 0 0 1
0 0 0 0`,
  },
  unix: {
    awk1: `ID   Name            Revenue
101  Rahul           12000.00
104  Sneha           14500.00
Total revenue generated by selected employees: 26500.00`,
    awk2: `Salary Details of Sales and Marketing
         Basic     DA        HRA       Gross
Total:   45000     11250     22500     78750
Average: 22500.00  5625.00   11250.00  39375.00`,
    awk3: `Input line:
10 20 30
Output:
10 20 30 60`,
    program1: `Enter 3 numbers:
23
89
41
89 is greater
23 is smaller`,
    program2: `Enter the value of n:
20
Enter the value of m:
5
20 is divisible by 5`,
    program3: `Enter the year:
2024
2024 is a leap year`,
    program4: `Choose your option: +
Enter two numbers: 12 8
Sum of 12 and 8 = 20`,
    program5: `Enter a string:
helloworld
Length of string:
10
First 3 character substring is
hel
Last 3 character substring is
rld
Enter the character to be searched:
o
Position of character o in a string is 5`,
    program6: `Enter a string:
operating
Enter the character to be searched:
t
Position of character t in a string is 6`,
    program7: `./program7.sh a b c
Arguments in the same order: a b c
Arguments in reverse order:
c
b
a`,
    program8: `Enter two file names:
test1.sh test2.sh
test1.sh has permission: rwxr-xr-x
test2.sh has permission: rw-r--r--`,
    program9: `./program9.sh file1.txt notes.doc
Renamed file1.txt to FILE1.TXT
Renamed notes.doc to NOTES.DOC`,
    program10: `./program10.sh dir1/dir2/dir3
Created directories for path: dir1/dir2/dir3`,
    prog1: `Enter the input string : Hi
Enter the total number of times the string to be displayed : 3
Result : Hi
Hi
Hi`,
    prog2: `perl prog2.pl 123 567
Sum of digits in 123 is : 6
Sum of digits in 567 is : 18`,
  },
  mp: {
    EXP01: `Key found at position : 02`,
    EXP02: `ENTER STRING :
MICROPROCESSOR
ENTERED STRING IS :
MICROPROCESSOR`,
    EXP03: `ENTER THE CHARACTER : A
Displayed hexadecimal value: 41`,
    EXP04: `ENTER THE STRING:
MALAYALAM
STRING IS PALINDROME`,
    EXP05: `FACTORIAL(6)=02D0`,
    EXP06: `THE FIBONACCI SERIES IS:
00 01 01 02 03 05 08 0D 15 22 37`,
    EXP07: `THE CURRENT TIME IS:
14:32:09`,
    EXP08: `WELCOME TO MICROPROCESSOR LAB`,
  },
  dbms: {
    'BOOK DEALER': `Database and tables created successfully.
Sample query result:
authorid  aname       qty_sold
111       sebesta     29
Catalogue prices updated for publisher 'Pearson'.`,
    bank_db: `All bank tables created and populated.
Sample output:
select * from branch;
5 rows returned.
Complex customer-branch queries executed successfully.`,
    insurance: `Insurance schema created and populated.
Sample query output:
NO_OF_ACC
8
Damage amount updated successfully for requested record.`,
    order_db: `Order processing tables created.
Sample listing:
CUSTNAME     NO_OF_ORDR   AVG_ORD_AMT
John Smith   5            18800.00
Raju         2            16000.00`,
    student_enroll: `Student enrollment schema created.
Sample query output:
dept
CS
Book list for top department returned successfully.`,
  },
};

const getSampleOutput = (courseName?: string, programName?: string): string => {
  if (!courseName || !programName) {
    return 'Sample output unavailable.';
  }

  const courseKey = courseName.toLowerCase();
  const decodedName = decodeURIComponent(programName);
  const courseOutputs = SAMPLE_OUTPUTS[courseKey];

  if (!courseOutputs) {
    return 'Sample output is not configured for this course yet.';
  }

  return (
    courseOutputs[decodedName] ??
    courseOutputs[decodedName.replace(/\.[^/.]+$/, '')] ??
    'Sample output not available for this specific program.'
  );
};

const ProgramDetails: React.FC = () => {
  const { courseName, programName } = useParams<Params>();
  const [programContent, setProgramContent] = useState<string>('');
  const [codeLanguage, setCodeLanguage] = useState<string>('text');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchProgramContent = async () => {
      try {
        if (!courseName || !programName) {
          setProgramContent('// Error: Course or program name not provided');
          setLoading(false);
          return;
        }

        // Decode the program name and map it to the correct file name
        const decodedProgramName = decodeURIComponent(programName);
        
        // Determine file extension based on course
        let fileName = '';
        if (courseName.toLowerCase() === 'daa') {
          fileName = `${decodedProgramName}.txt`;
        } else if (courseName.toLowerCase() === 'mp') {
          fileName = `${decodedProgramName}.ASM`;
        } else if (courseName.toLowerCase() === 'dbms') {
          fileName = `${decodedProgramName}.sql`;
        } else if (courseName.toLowerCase() === 'unix') {
          // For UNIX, we'll try multiple approaches to find the correct file
          // First, check if the programName already includes an extension
          if (decodedProgramName.includes('.')) {
            // If the programName already has an extension, use it as-is
            fileName = decodedProgramName;
          } else {
            // If no extension, try to determine the correct one
            // We'll try common extensions in order of priority
            const extensionsToTry = ['.txt', '.sh', '.pl', '.awk', '']; // Note: empty string for files without extension
            
            let found = false;
            for (const ext of extensionsToTry) {
              const testFileName = `${decodedProgramName}${ext}`;
              try {
                const response = await fetch(`/data/${courseName.toLowerCase()}/${testFileName}`);
                
                if (response.ok) {
                  // Check if the response is actually text content and not HTML
                  const content = await response.text();
                  
                  // If content starts with '<' it might be HTML, so we should try the next extension
                  if (!content.trim().startsWith('<')) {
                    fileName = testFileName;
                    setProgramContent(content);
                    setCodeLanguage(inferLanguage(courseName, testFileName));
                    found = true;
                    break;
                  }
                }
              } catch (err) {
                // Continue to next extension if there's an error
                continue;
              }
            }
            
            if (!found) {
              // If no file found with any extension, try the original name as-is
              fileName = decodedProgramName;
              setProgramContent(`// Error: Could not find file ${decodedProgramName} with common extensions`);
              setLoading(false);
              return; // Exit early since we've handled the response
            }
          }
        }

        // If we reach here, fileName has been set
        if (!fileName) {
          setProgramContent('// Error: Could not determine file name');
          setLoading(false);
          return;
        }

        // Only fetch if the content hasn't been set yet (in the loop above)
        // If fileName is already set but programContent is still empty, fetch the content
        if (programContent === '') {
          const response = await fetch(`/data/${courseName.toLowerCase()}/${fileName}`);

          if (response.ok) {
            const content = await response.text();
            // Check if the content looks like HTML (starts with <html>, <head>, <body>, etc.)
            if (content.trim().startsWith('<')) {
              setProgramContent(`// Error: Unexpected HTML content received instead of program code\n// File: ${fileName}\n// Please check if the file exists and is accessible`);
              setCodeLanguage('text');
            } else {
              setProgramContent(content);
              setCodeLanguage(inferLanguage(courseName, fileName));
            }
          } else {
            setProgramContent(`// Error: Could not load program content\n// File: ${fileName}\n// Status: ${response.status} ${response.statusText}`);
            setCodeLanguage('text');
          }
        }
      } catch (error) {
        console.error('Error fetching program content:', error);
        setProgramContent('// Error: Could not load program content due to network error');
        setCodeLanguage('text');
      } finally {
        setLoading(false);
      }
    };

    fetchProgramContent();
  }, [courseName, programName]); // Dependencies array is correct

  // Get associated downloads for UNIX programs
  const getAssociatedDownloads = () => {
    if (courseName?.toLowerCase() !== 'unix' || !programName) return [];
    
    const decodedProgramName = decodeURIComponent(programName);
    // Check if the program name matches awk1, awk2, or awk3 (without extension)
    const baseName = decodedProgramName.split('.')[0]; // Split by dot and take first part
    const assocFiles: Record<string, string[]> = {
      'awk1': ['sales_data'],
      'awk2': ['emp'],
      'awk3': ['textfile']
    };
    
    return assocFiles[baseName] || [];
  };

  const navLinks = courseName
    ? [
        { to: '/', label: 'Home' },
        { to: `/course/${courseName}`, label: courseName },
      ]
    : [{ to: '/', label: 'Home' }];

  const associatedDownloads = getAssociatedDownloads();
  const sampleOutputPrefix =
    'This is just a sample output and ai generated , it may be wrong';
  const sampleOutput = loading
    ? 'Loading sample output...'
    : getSampleOutput(courseName, programName);

  return (
    <div className="site-wrapper">
      <Header links={navLinks} />

      <main style={{ paddingTop: '80px' }}>
        <div className="full-program-layout">
          <div className="program-section">
            <h3>Program Code</h3>
            <div className="program-code-full">
              <SyntaxHighlighter
                language={codeLanguage}
                style={oneDark}
                customStyle={{ margin: 0, borderRadius: '8px' }}
                showLineNumbers
                wrapLongLines
              >
                {loading ? 'Loading program...' : programContent}
              </SyntaxHighlighter>
            </div>
            
            {/* Show associated download buttons for UNIX programs */}
            {associatedDownloads.length > 0 && (
              <div style={{ marginTop: '20px' }}>
                <h4>Data Files:</h4>
                {associatedDownloads.map((fileName, index) => (
                  <a
                    key={index}
                    href={`/data/${courseName!.toLowerCase()}/${fileName}`}
                    download={fileName}
                    className="download-btn"
                    style={{
                      display: 'inline-block',
                      padding: '8px 16px',
                      margin: '5px',
                      backgroundColor: '#007bff',
                      color: 'white',
                      textDecoration: 'none',
                      borderRadius: '4px',
                      border: 'none',
                      cursor: 'pointer'
                    }}
                  >
                    Download {fileName}
                  </a>
                ))}
              </div>
            )}
          </div>

          <div className="output-section">
            <h3>Sample Output</h3>
            <div className="output-content">
              <p className="sample-output-disclaimer">{sampleOutputPrefix}</p>
              <SyntaxHighlighter
                language="text"
                style={oneDark}
                customStyle={{ margin: 0, borderRadius: '8px' }}
                wrapLongLines
              >
                {sampleOutput}
              </SyntaxHighlighter>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default ProgramDetails;